server:
  port: 8000
spring:
  application:
    name: shopmall-auth

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shopmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 13875780121


  redis:
    host: 192.168.210.128
    port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

token:
  secret: asdjkahsdhjahfkjasjdhaksjdhajskdhj
  tokenHeader: access_token
  expire: 3600



ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000




