spring:
  application:
    name: shopmall-gateway
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://shopmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: ware_route
          uri: lb://shopmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: auth_route
          uri: lb://shopmall-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://shopmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



server:
  port: 7010


ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

gatewayfilter:
  whitepath:
    - /api/auth/login
    - /api/auth/register
    - /api/auth/sendSms
    - /api/product/category/list/tree
    - /api/spuinfo