server:
  port: 7050
spring:
  application:
    name: shopmall-kill

  task:
    execution:
      pool:
        core-size: 50
        max-size: 100
    scheduling:
      pool:
        size: 30

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopmall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 13875780121


  redis:
    host: 192.168.210.128
    port: 6379
    database: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动确认消息

      direct:
        acknowledge-mode: manual
        retry:
          enabled: true



# mybatis-plug
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ribbon
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000



logging:
  level:
    com.alibaba.nacos: WARN

