server:
  port: 7010

spring:
  application:
    name: shopmall-search

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopmall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 13875780121